#ifndef __RetroMessengerCertDlg__
#define __RetroMessengerCertDlg__

/**
@file
Subclass of CertDlg, which is generated by wxFormBuilder.
*/

#include "RetroMessenger_GUI.h"

/** Implementing CertDlg */
class RetroMessengerCertDlg : public CertDlg
{
protected:
	// Handlers for CertDlg events.
	void OnOk( wxCommandEvent& event );
	void OnCancel( wxCommandEvent& event );
	void OnSave( wxCommandEvent& event );
	
public:
	/** Constructor */
	RetroMessengerCertDlg( wxWindow* parent );
	void DisplayCertificate( const std::string& path );
	void DisplayErrorMessage( const std::string& errorMessage );
};

#endif // __RetroMessengerCertDlg__
